config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index]
  resources :orders, only: [:create, :destroy]
  scope '/admin' do
    resources :posts, only: [:update, :index]
  end
  root 'welcome#index'
  get 'welcome/index'
  get 'addnews', to: 'welcome#addnews'
  post 'welcome/download'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name,
            presence: true,
            format: { with: /[а-яА-ЯёЁa-zA-Z\s\-]+/u }
  validates :number,
            presence: true,
            format: { with: /(\+)?\d{7,12}/ }

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, :image, presence: true
  validates :title, length: {maximum: 150}
  validates :body, length: {maximum: 500}
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin'

  def index
    @orders = Order.all.reverse_order
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin', only: :destroy

  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.js
      else
        format.js
      end
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to admin_index_path
  end

  private
  def order_params
    params.require(:order).permit(:number, :name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin'

  def index
    @posts = Post.first(3)
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :image, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @order = Order.new
    @posts = Post.all
    #Post.new(:image => 'https://pp.userapi.com/c841121/v841121119/44126/jWgz51f-Z3U.jpg', :title => 'Открыт новый набор на группы от 5 лет с января 2018', :body => 'Открыт новый набор на группы от 5 лет с января 2018').save!
  end

  def download
    send_file("#{Rails.root}/public/files/#{params[:file_name]}")
  end

  def addnews 
  	Post.new(:image => 'https://pp.userapi.com/c834301/v834301119/4a0ee/d7nw02WwVf8.jpg', :title => 'Всем мальчикам скидка на протяжении года 10%', :body => 'Всем мальчикам скидка на протяжении года 10%').save!
  	Post.new(:image => 'https://pp.userapi.com/c841121/v841121119/44126/jWgz51f-Z3U.jpg', :title => 'Открыт новый набор на группы от 5 лет с января 2018', :body => 'Открыт новый набор на группы от 5 лет с января 2018').save!
  	Post.new(:image => 'https://pp.userapi.com/c841121/v841121119/44126/jWgz51f-Z3U.jpg', :title => 'Открыт новый набор на группы от 5 лет с января 2018', :body => 'Открыт новый набор на группы от 5 лет с января 2018').save!
  end

end

app/views/admin/index.html.erb
<div class="container"><h1>Панель администратора</h1></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="tabs">
        <ul class="nav nav-tabs">
          <li class="active">
            <%= link_to 'Заявки', admin_index_path, data_toggle: 'tab' %>
          </li>
          <li>
            <%= link_to 'Новости', posts_path, data_toggle: 'tab' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="tab-content">
  <div id="panel1" class="tab-pane fade in active">
    <div class="container">
      <h3>Список заявок:</h3>
      <p>
      <div class="list-group">
        <%= render @orders %>
      </div>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Школа танцев</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" >
     <link rel="icon" href="Falcon-6.gif" type="images/gif">
  <meta name="viewport" content="width=device-width, inicial-scale=1.0">
</head>

<body id="ml-dalos" class="artur-cherkanov">
<%= yield %>
</body>
</html>

app/views/orders/_order.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Имя: <%= order.name %> | Номер: <%= order.number %> | Дата: <%= order.created_at %></p> <%= button_to 'X',order, method: :delete,  data: {confirm:  'Вы уверены?'}, class: 'close btn' %>
  </div>
</div>

app/views/orders/create.js.erb
document.getElementById('subscribe').addEventListener('ajax:success', function (event) {
    <% if @order.errors.any? %>
    document.getElementById('message-field').innerHTML = "Вы ввели неверные данные";
    <% else %>
    document.getElementById('message-field').innerHTML = 'Ждите звонка!';
    <% end %>
});

app/views/posts/_post.html.erb
<br/>
<div class="posts panel row">
  <%= form_for post do |f| %>
      <div class="col-lg-3">
        <div class="row">
          <img data-toggle="tooltip" title="Нажмите чтобы заменить картинку" class="upload_widget_opener" id="<%= post.id %>" src="<%= post.image %>">
        </div>
        <div class="row">
          <br/><%= f.submit 'Сохранить', class: 'btn btn-primary' %>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="input-group col-lg-12 ">
          <%= f.text_field :image, id: "#{post.id}_field", type: 'hidden' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="input-group col-lg-12 ">
          <%= f.text_area :body, class: 'form-control', rows: 5 %>
        </div>
      </div>
  <% end %>

</div>

app/views/posts/index.html.erb
<div class="container"><h1>Панель администратора</h1></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="tabs">
        <ul class="nav nav-tabs">
          <li>
            <%= link_to 'Заявки', admin_index_path, data_toggle: 'tab' %>
          </li>
          <li class="active">
            <%= link_to 'Новости', posts_path, data_toggle: 'tab' %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="tab-content">
  <div id="panel1" class="tab-pane fade in active">
    <div class="container">
      <h3>Редактирование новостей:</h3>
      <%= render @posts %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $('.upload_widget_opener').on('click', function () {
        var id = this.id;
        var field_id = id + '_field';
        cloudinary.openUploadWidget({cloud_name: 'dg0xjrcbv', upload_preset: 't5t3uxu9'},
            function (error, result) {
                console.log(error, result);
                document.getElementById(id).setAttribute("src", result[0].secure_url);
                document.getElementById(field_id).setAttribute("value", result[0].secure_url);
            });
    });
</script>

app/views/welcome/index.html.erb
<div class="n-2 navbar navbar-inverse navbar-fixed-top"> </div>
<div class="n-1 navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left" style="font-family: Monospaced">
        <li  class="active"><a href="#wb">О нас</a></li>
        <li><a href="#teach">Преподаватели</a></li>
        
        <li><a href="#dg-1" class="disabled">Галерея</a></li>
        <li><a href="#lg">Новости</a></li>
        <li><a href="#r">Записаться</a></li> 
        <li><a href="#f">Контакты</a></li>
        <li>
          <!--  <a data-toggle="modal" data-target=".bd-modal-sm" href="#" class="disabled">Договор</a></li>   -->
       </ul>
    </div>
  </div>
</div>
<div id="documents" class="modal fade bd-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <%= button_to 'X', root_path, method: :get, class: 'btn close' %>
        <h1 class="modal-title">Скачать документы:</h1>
      </div>
      <hr>
      <div class="modal-body row">
        <div class="col-sm-12">
          <%= link_to welcome_download_path(file_name: 'dogovor.doc'), method: :post do %>
              <i class="fa fa-download" aria-hidden="true"></i>
              Договор
          <% end %>
          <br/>
          <%= link_to welcome_download_path(file_name: 'anketa-zayavlenie.docx'), method: :post do %>
              <i class="fa fa-download" aria-hidden="true"></i>
              Анкета
          <% end %>
          <br/>
          <%= link_to welcome_download_path(file_name: 'odezhda.doc'), method: :post do %>
              <i class="fa fa-download" aria-hidden="true"> </i>
              Одежда
          <% end %>
          <br/>
          <%= link_to welcome_download_path(file_name: 'pravila_shkoly_tantsev.docx'), method: :post do %>
              <i class="fa fa-download" aria-hidden="true"></i>
              Правила
          <% end %>
          <br/>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="up">
  <a href="#headerwrap" style="color: #7b7b7b">
    <p class="pPageScroll"><i class="fa fa-chevron-up fa-3x" aria-hidden="true"></i></p></a></div>
<div id="headerwrap" style="background-image: url(salsa.jpg)">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8">
        <img id="Falcon"align="left" src="Falcon.png">
      </div>
    </div>
  </div>

</div>
<div id="wb">
  <div class="container-fluid wb">
    <div class="row centered">
      <h1>Наши услуги</h1>
      <div class=" centered col-lg-6 col-md-6 col-sm-12 col-xs-12 hovereffect-container">
        <div class="hovereffect">
          <img class="img-1 img-responsive" src="de.webp" alt="">
          <div class="overlay">
            <h2>Обучение танцам</h2>
            <p>
              Европейские танцы<br>
              &nbsp;&nbsp;&nbsp;Медленный вальс<br>
              &nbsp;&nbsp;&nbsp;Танго<br>
              &nbsp;&nbsp;&nbsp;Венский вальс<br>
              &nbsp;&nbsp;&nbsp;Фокстрот<br>
              &nbsp;&nbsp;&nbsp;Квикстеп<br><br>
              Латиноамериканские танцы<br>
              &nbsp;&nbsp;&nbsp;Самба<br>
              &nbsp;&nbsp;&nbsp;Ча-ча-ча<br>
              &nbsp;&nbsp;&nbsp;Румба<br>
              &nbsp;&nbsp;&nbsp;Джаив<br>
              &nbsp;&nbsp;&nbsp;Пасодобль<br>
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 hovereffect-container">
        <div class="hovereffect">
          <img class="img-2  img-responsive" src="cp.jpg" alt="">
          <div class="overlay">
            <h2>Детская хореография</h2>
            <p>
              Дети, занимающиеся танцами, развиваются гораздо быстрее и достигают больших успехов в жизни,
              чем их
              ровесники, которые не танцуют. Много докторов признают, что программа танцев для детей дает
              не только
              обучение классическим и современным направлениям, но и предлагает решение многих проблем,
              таких как
              скованность, стеснительность.
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 hovereffect-container">
        <div class="hovereffect">
          <img class="img-3 img-responsive" src="md.jpg" alt="">
          <div class="overlay">
            <h2>Свадебный танец</h2>
            <p>
              Медленный вальс Аргентинское танго<br>
              Акробатический рок& ролл (или линдихоп)<br>
              Модерн, сальса, бачата<br>
              Латина (румба, ча-ча-ча)<br>
              Свадебный микс
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 hovereffect-container">
        <div class="hovereffect">
          <img class="img-4 img-responsive" src="pe.jpg" alt="">
          <div class="overlay">
            <h2>Выступления</h2>
            <p>
              Турниры<br>
              &nbsp;&nbsp;&nbsp;Клубные<br>
              &nbsp;&nbsp;&nbsp;Городские<br>       
              &nbsp;&nbsp;&nbsp;Республиканские<br><br>
              Различные мероприятия<br>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="teach">
  <div class="container-fluid w">
    <div class="row centered">
      <h1>Наши тренеры</h1>

      <div class="col-lg-6">
        <h4>Анастасия Александровна Сокольчик</h4>
        <div id="sl"

             class="fotorama"
             data-width="100%"
             data-height="70%"
             data-arrows="false"
             data-nav="false"
             data-loop="true"
             data-fit="cover">
          <a data-fit="scaledown"><img src="IMG_64532.jpg" width="144" height="96"></a>
          <a data-fit="scaledown"><img src="m2VWESUYW-U.jpg" width="144" height="96"></a>

        </div>
        <!-- <img class="ds" src="IMG_64532.jpg"> -->
        <div class="text-center">
          Руководитель студии, мастер спорта, чемпионка РБ, финалист и полуфиналист республиканских
          и международных соревнований, выпускница Белорусского государственного университета культуры и
          искусства по
          специальности бальный танец, обучалась у лучших тренеров мира, принимает активное участие в
          семинарах по
          повышению квалификации как в Республике Беларусь, так и за её пределами, любит свою профессию,
          ответственно
          подходит к вопросу подготовки детей, добрая, но в то же время требовательная, найдёт подход к
          любому ученику,
          поможет раскрыть талант и достичь хороших результатов
        </div>            <!--data-height="450px"-->

        <div>
          <input type="button" class="btn btn-link btn-2" value="Узнать больше">
        </div>
      </div>
      <div class="col-lg-6">
        <h4>Алеся Николаевна Макаревич</h4>
        <div id="sl"

             class="fotorama"
             data-minwidth="100%"
             data-height="70%"
             data-nav="false"
             data-allowfullscreen="false"
             data-arrows="false"
             data-loop="true"
             data-fit="cover">
          <a data-fit="scaledown"><img src="IMG_5990.jpg" width="100%" height="96"></a>
          <a data-fit="scaledown"><img src="qxLgs6p5mEM.jpg" width="144" height="96"></a>

        </div>
        <!--<img class="ds" src="">-->
        <div class="text-center">
          Мастер спорта по спортивным танцам, чемпионка РБ, с 2014 года является членом национальной
          сборной команды
          формейшн, является действующим танцором, многократная финалистка и призер Республиканских и
          Международных
          соревнований, строгий и требовательный тренер, умеющий к каждому ребенку найти индивидуальный и
          трепетный
          подход, её цель из всех учеников сделать звёзд паркета
        </div>
        <div>
          <input type="button" class="btn btn-link btn-1" value="Узнать больше">
        </div>
      </div>

    </div>
  </div>
</div>

<div id="dg">
  <div class="container-fluid">
    <div class="row centered">
      <h4>Галерея</h4>

      <div id="dg-1"
           data-hash="false"
           data-nav="false"
           class="fotorama"
           data-minwidth="100%"
           data-height="100%"
           data-arrows="false"
           
           data-loop="true"
           data-fit="cover"
        <a data-fit="scaledown"><img src="6N6iC_Ns-U8.jpg" width="144" height="96"></a>
        <a><img src="image1.jpg" width="144" height="96"></a>
        <a data-fit="scaledown"><img src="image3.jpg" width="144" height="96"></a>
        <a><img src="image2.jpg" width="144" height="96"></a>
      </div>

    </div>
  </div>
</div>
<div id="lg">
  <div class="container">
    <div class="row centered">
      <h4>Наши новости</h4>
      <div class="col-lg-4">
        <div class="thumbnail">
          <h1><%= @posts[0].title %></h1>
          <img src="<%= @posts[0].image %>">
          <%= @posts[0].body %>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="thumbnail">
          <h1><%= @posts[1].title %></h1>
          <img src="<%= @posts[1].image %>">
          <%= @posts[1].body %>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="thumbnail">
          <h1><%= @posts[2].title %></h1>
          <img src="<%= @posts[2].image %>">
          <%= @posts[2].body %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="r">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2">
        <h4>Записаться на пробный урок</h4>
        <br><br>
        <div class="subscribe" id="subscribe">
          <%= form_for @order, remote: true do |f| %>
              <%= f.text_field :name, placeholder: 'Введите имя' %>
              <%= f.text_field :number, placeholder: 'Введите номер' %>
              <%= f.submit 'Записаться', id: 'order_btn' %>
          <% end %>
          <div id="message-field"></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="f">
  <div class="container">
    <div class="f-1 row centered">
      <div class="row linkrow">
        <div class="col-lg-3">
          <a href="https://goo.gl/maps/MNXcLnNBKpE2" target="_blank" class="i">Ратомская Средняя Школа</a>
        </div>
        <div class="col-lg-3">
          <a href="https://goo.gl/maps/dVpzxmTikuk" target="_blank" class="i">М-н Сокол, Средняя школа
            194</a>
        </div>
        <div class="col-lg-3">
          <a href="https://goo.gl/maps/GLnBpMzXkNE2" target="_blank" class="i">ДК Ритм, ул.Асаналиева
            48а</a>
        </div>
        <div class="col-lg-3">
          <a href="https://goo.gl/maps/KKXJMv4gHuS2" target="_blank" class="i">Замосточская средняя
            школа</a>
        </div>
      </div>
      <a onclick="alert('Извините, социальные сети пока недоступны!')"><i class="fa fa-facebook"></i></a>
      <a onclick="alert('Извините, социальные сети пока недоступны!')"><i class="fa fa-vk"></i></a>
      <a onclick="alert('Извините, социальные сети пока недоступны!')"><i class="fa fa-instagram"></i></a>
    </div>
    <div class="row centered">
    <a style="color: darkgray;" href="tel:+375291550999">+375291550999</a>
    </div>
  </div>
</div>